### PR TITLE
Doc: Migrating documentation to MD and within modules

### LINKED ISSUE #636: Doc: Update cv_container_v3 page to include image bundle information
[cv_container_v3](https://cvp.avd.sh/en/stable/docs/how-to/v3/cv_container_v3/) is missing information related to add/detaching image bundles to containers

### LINKED ISSUE #643: Doc: Add syntax highlighting to all module documentation
### Enhancement summary

The current v3 module documentation has an example included. The example does not have syntax highlighting. I think it would be a great style addition to update the conversion script to add syntax highlighting in this block.

### Which component of AVD is impacted

other

### Use case example

Only impact docs

### Describe the solution you'd like

Add Syntax highlighting to all examples

### Describe alternatives you've considered

N/A

### Additional context

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #673: Doc: improve documentation automation
### Issue Summary

Right now for instance lists in strings from python files are not rendered and they are instead put in one single paragraph

### Which component(s) of AVD impacted

other

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Input variables

_No response_

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #674: Reference examples within the repo for examples
### Enhancement summary

Many examples now exist within the repository, these examples should be referenced in the documentation site. For example, within the how-to section.

### Which component of AVD is impacted

other

### Use case example

Please see admonitions in the [material](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) for mkdocs examples

### Describe the solution you'd like

Please see note above

### Describe alternatives you've considered

N/A

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JulioPDX**
## Change Summary

- Move away from RST to generate documentation
- doc.py file will read modules directory and generate the relevant markdown docs, no more intermediate with RST
- Make file updates for new pointers to directories and script
- Moved duplicate information from how-to section to live within the modules documentation
- Deleted old files under how-to directory
- Updated mkdocs with removal of how-tos relevant to modules
- Created new output folder that can be used to display module output within module documentation
- Updated link check workflow to match newer style with AVD

## Related Issue(s)

Fixes #673
Fixes #674
Fixes #636 
Fixes #643 

## Component(s) name

Docs

## Proposed changes

Proposed changes listed under summary.

## How to test

Locally install requirements and run `mkdocs serve`

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly. (check the box if not applicable)
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by sugetha24** [comment]
Can we bump the min supported CVP version to 2021.2 according to [EOL](https://www.arista.com/en/support/advisories-notices/end-of-support/17253-end-of-software-support-for-cloudvision-portal-2021-2-release-train) notice.
@carlbuchmann maybe a PSA to the field might be needed?

**Comment by JulioPDX** [comment]
> Can we bump the min supported CVP version to 2021.2 according to [EOL](https://www.arista.com/en/support/advisories-notices/end-of-support/17253-end-of-software-support-for-cloudvision-portal-2021-2-release-train) notice. @carlbuchmann maybe a PSA to the field might be needed?

It may need to be higher, since 2021.2 reached EOL on Sep 2023

**Comment by sugetha24** [comment]
> > Can we bump the min supported CVP version to 2021.2 according to [EOL](https://www.arista.com/en/support/advisories-notices/end-of-support/17253-end-of-software-support-for-cloudvision-portal-2021-2-release-train) notice. @carlbuchmann maybe a PSA to the field might be needed?
> 
> It may need to be higher, since 2021.2 reached EOL on Sep 2023

yes. My bad, I meant to say we need to bump supported version to 2021.3 and up!

**Review by sugetha24 — APPROVED** [review]
LGTM

**Review by sugetha24 — APPROVED** [review]

**Review by noredistribution — COMMENTED** [review]
Wow, awesome job! Thanks for doing this! 
Since we are updating the docs can we also fix some of the typos we have?
Only found one where the configlet_v3 example references v1 in https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/modules/cv_configlet_v3.py#L75

otherwise lgtm!

**Review by sugetha24 — APPROVED** [review]

**Review by carlbuchmann — APPROVED** [review]
LGTM

**Comment by carlbuchmann** [comment]
> Only found one where the configlet_v3 example references v1 in https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/modules/cv_configlet_v3.py#L75

fixed in: [124908f](https://github.com/aristanetworks/ansible-cvp/pull/678/commits/124908f9255c6a10da7e37542db3553786e42016)

**Pull request merged**
