### PR TITLE
Feat: Implement initial module for image management phase1

### LINKED ISSUE #419: Add support for image management
### Enhancement summary

Currently there is no way to manage either images of image bundles. This feature request covers two things;

- An ansible module to support image management e.g. add/list/remove an image, add / list / remove an image bundle
- Support for applying an image bundle to a device or to a container

### Which component of AVD is impacted

other

### Use case example

Image management is not currently covered in `ansible-cvp`

Sample use case would be to;

1. Upload a new EOS / Extension image
2. Create a bundle based on the new images
3. Assign this bundle to a device/container

### Describe the solution you'd like

1. Create a new cv_images module to allow for adding / listing / deleting of images and image bundles
2. ?(potentially)? Enhance existing modules to support image management e.g. assigning of image bundles to devices/containeres

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by colinmacgiolla**
## Change Summary

This PR adds support to the `arista.cvp.cv_facts` module to gather `imageBundle` and `image` information. It also provides the `arista.cvp.cvp_image` module, to allow images to be added, as well as to create, modify and delete image bundles

## Related Issue(s)

Fixes #419 

## Component(s) name
`arista.cvp.cv_facts`
`arista.cvp.cv_image_cv3`

## Proposed changes

- arista.cvp.cv_facts 
  -  Implement collection of `images` and `imageBundles` - no changes to existing data model
  - This is planned to be deprecated in favour of _v3, but no harm in filling the hole in the meantime
- arista.cvp.cv_image_v3
  - Create the `arista.cvp.cv_image_v3` module
  - Supported modes are `image` or `bundle`
  - We can get or add `images`, removing images via `cvprac` is not currently supported
  - We can get, add, update, and remove `bundles`
    - Note that the `bundle` `add` action will implicitly update a bundle, if it already exists

### arista.cvp.cv_image_v3 data model
```yaml
mode: < image | bundle >
action: < get | add | remove >
image: < Image file name >
image_list:
   - < Image 1 for bundle >
   - < Image 2 for bundle >
bundle_name: <Image bundle name">
```

## Caveats
- When uploading large images, the connection may time out with the default settings. The solution is to add the following `vars` to the task
```yaml
      vars: 
        ansible_command_timeout: 1200
        ansible_connect_timeout: 600
```
- When removing a bundle, if the image contained within the bundle is not in use anywhere else, it will be deleted

## How to test
Full runbook tested using latest ansible-cvp against CVP `2021.2.0`

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly. (check the box if not applicable)
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by colinmacgiolla** [comment]
@titom73 - should I name this a v3 module?
I left it without, since there was never an older one, but if we are going for currently maintained = v3+, then it makes sense to name it that way for consistency.

**Comment by noredistribution** [comment]
I vote yes for making this v3, we could probably just make all the v1 facts as v3 too, shouldn't take long to migrate, but will let @titom73 @guillaumeVilar to chime in too, I can help with the migration

**Comment by titom73** [comment]
Indeed, as v1 modules will be deprecated soon and removed in a future version, `cv_image` should be renamed to `cv_image_v3`.

Also, starting with v3, all modules are independant and should not require a call to `cv_facts` as execution time of this module can be very long.

**Review by guillaumeVilar — COMMENTED** [review]
+1 for v3 module. 
Also, could we have a class-based module (same as for other modules)? 
This will make it easier to integrate the module into our test suite.

**Comment by colinmacgiolla** [comment]
Take a look and see what you think.
All tests out ok

**Comment by guillaumeVilar** [comment]
Thanks a lot! 
So 2 things: 

1. When writing the documentation, we might want to give an example of how to tune the ansible timeouts. Without changing them, uploading an EOS image to CVP fails with a `msg": "('Connection aborted.', timeout('The write operation timed out'))"` error message. 
This is an example of how to change the timeouts: 
```
  tasks:
    - name: Add EOS image EOS-4.27.1F.swi to CVP
      vars: 
        ansible_command_timeout: 1200
        ansible_connect_timeout: 600
      arista.cvp.cv_image_v3:
        image: EOS-4.27.1F.swi
        mode: image
        action: add
      register: debug
```

2. It seems that in some situations the extension got removed from CVP when: 
* The image bundle get updated with a new extension
* The 'old' extension is not used in any other image bundle 
This doesn't seem to be an issue with your code but with the handling of the API call on the CVP side. 
It might be worth mentioning in the documentation as well...

**Comment by titom73** [comment]
### Done

- Add DOCMENTATION docstring
- Run ansible-test to lint python code
- Reset change in arista.cvp.cv_facts
- Rebuild webdoc

### Todo: 

- Enforce `required: false|true` in DOCUMENTATION.options
- Create test cases (require PR #437 for mock process)

**Review by titom73 — APPROVED** [review]
LGTM!

**Pull request merged**
