### PR TITLE
Make: Implement editorconfig settings

### PR DESCRIPTION
**Pull request by titom73**
## Change Summary

Add [`.editorconfig`](https://editorconfig.org/#overview) to make code edition easier and more generic.

## Component(s) name

N/A

## Proposed changes

Add an `.editorconfig` file with editor parameters

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly. (check the box if not applicable)
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by ClausHolbechArista** [comment]
is this better than having a `.vscode/` folder with settings?

**Comment by titom73** [comment]
> is this better than having a .vscode/ folder with settings?

It is because editorConfig is not linked to a specific text editor and it is probably nice to have basic settings shared for most of text editors.

https://editorconfig.org/#pre-installed

**Review by ClausHolbechArista — APPROVED** [review]
LGTM

**Comment by titom73** [comment]
Will be reopened if it makes sense after cleanup session

**Pull request closed without merging**
