### PR TITLE
CV Modules improvments

### PR DESCRIPTION
**Pull request by titom73**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [x] Other (please describe):Major version upgrade of `arista.cvp.cv_*` modules

## Related Issue(s)

N/A

### Overview

- Speed-up execution time
- Remove cv_facts need
- Keep intended config approach: create / delete topology
- Keep ansible `--check` mode support
- Add support for hostname, serial-number, mac-address
- Remove filters as much as possible

### Work status

- [x] cv_container
- [x] cv_configlet
- [x] cv_device
- [ ] cv_facts
- [x] Module tools:
	- [x] Ansible Output manager: IN PROGRESS
	- [x] Function cleanup

Demo GIST: https://gist.github.com/titom73/8c8309a292ad2d62b09bfa5c74d27320

Modules documentation: https://cvp.avd.sh/en/devel-3.x/

### cv_container

__Features__

- No cv_facts
- Create Containers from user inputs
- Attach configlet listed in user inputs to containers
  - configlet attachment using CV interface are not changed
- Remove containers
- Support of ansible check mode
  - Known limitation: container relation that could generate a partial diff

### cv_configlet

__Features__

- Create configlets
- Update configlets
- Delete configlets
- Diff report
- Changes report
- Check mode

### cv_device

__Features__

- Move device to container
- Attach configlets
- Deploy device from undefined
- Changes report
- Check mode support

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/aristanetworks/ansible-cvp/blob/master/contributing.md#branches) document.
- [ ] All new and existing tests passed (`make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by guillaumeVilar** [comment]
Hi, 

I tested the following playbook (creation of 2 configlets and 4 empty containers with the created configlet attached to the last container **on CVP running 2020.3.0**: 
```
- hosts: cv_server
  vars:
    containers:
      A:
        parent_container: Tenant
      B:
        parent_container: A
      C:
        parent_container: B
      D:
        parent_container: C
        configlets: 
          - 'vlan700'
          - 'vlan701'

    CVP_CONFIGLETS:
      vlan700: "vlan 700"
      vlan701: "vlan 701"

  tasks:
    - name: "Create configlet vlan 700 and 701 on {{inventory_hostname}}"
      arista.cvp.cv_configlet_v3: 
        configlets: "{{CVP_CONFIGLETS}}"
        state: present
      
    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container_v3:
        topology: "{{containers}}"
        state: present

```

* It ran in 24 seconds in total without any issue: 
```
(venv) ~/Documents/avd-base-repo$ date && ansible-playbook cvp-test.yml && date
Fri  5 Mar 2021 18:09:51 GMT


PLAY [cv_server] *****************************************************************************************************************************************************************************************************************

TASK [Create configlet vlan 700 and 701 on cv_server] ****************************************************************************************************************************************************************************
ok: [cv_server]

TASK [Build Container topology on cv_server] *************************************************************************************************************************************************************************************
ok: [cv_server]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************
cv_server                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Fri  5 Mar 2021 18:10:15 GMT
```

* With no cv_fact needed

* The expected topology was seen on the CVP UI, so all good. 


A couple of observations: 
- The tasks are marked as `ok` in ansible despite the fact that the state of CVP clearly changed. Could we have the task that is marked as `changed` in case of change being made on the CVP server? 
- I tried the direct deletion action (present --> absent): the containers were deleted, but the configlets were still present on the CVP server. I guess it is because I tried to delete configlets attached to some containers. I think we should handle that case as for now the task is marked as completed, we should fail the task imho. 

Let me know what you think. 

But very good improvements overall.

**Comment by titom73** [comment]
Hello @guillaumeVilar 

Thanks for the report.

- `changed` flag is now supported on cv_configlet_v3
- In your setup, moving state from present to absent means you have to run cv_container first and then cv_configlet.

Indeed, cv_configlet only create/update/delete and the deletion happens only if configlet is not attached to any resource.

**Comment by guillaumeVilar** [comment]
Hi, I tested again the cv_container_v3 module, I have the following error: 
```
(venv) ~/Documents/avd-base-repo$ ansible-playbook cvp-test.yml
PLAY [cv_server] ************************************************************************************************************************************************************************************************************

TASK [Create configlet vlan 700 and 701 on cv_server] ***********************************************************************************************************************************************************************
changed: [cv_server]

TASK [Build Container topology on cv_server] ********************************************************************************************************************************************************************************
fatal: [cv_server]: FAILED! => changed=false 
  msg: |-
    Error, your input is not valid against current schema:
     {'A': {'parent_container': 'Tenant'}, 'B': {'parent_container': 'A'}, 'C': {'parent_container': 'B'}, 'D': {'parent_container': 'C', 'configlets': ['vlan700', 'vlan701']}}

PLAY RECAP ******************************************************************************************************************************************************************************************************************
cv_server                  : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

It seems that this JSON is not validated (see below - from `plugins/modules/cv_container_v3.py`): 
```
    if user_topology.is_valid is False:
        ansible_module.fail_json(
            msg='Error, your input is not valid against current schema:\n {}'.format(ansible_module.params['topology']))
```

Here is the ansible-playbook I used (same as in my last comment): 
```
- hosts: cv_server
  vars:
    containers:
      A:
        parent_container: Tenant
      B:
        parent_container: A
      C:
        parent_container: B
      D:
        parent_container: C
        configlets: 
          - vlan700
          - vlan701


    CVP_CONFIGLETS:
      vlan700: "vlan 700"
      vlan701: "vlan 701"

  tasks:
    - name: "Create configlet vlan 700 and 701 on {{inventory_hostname}}"
      arista.cvp.cv_configlet_v3: 
        configlets: "{{CVP_CONFIGLETS}}"
        state: present
      
    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container_v3:
        topology: "{{containers}}"
        state: present
```

I'm not sure what I did wrong, this topology seems fine to me...

Thanks, 
Guillaume

**Comment by noredistribution** [comment]
It seems like "parent_container" is not valid anymore, the new key name is "parentContainerName"
when enabling debugging I saw this

```
2021-03-14 17:54:36,681 - arista.cvp.json_schema: ERROR - func: validate_cv_inputs (L:326) - Invalid inputs 'parentContainerName' is a required pro     perty
2169
2170 Failed validating 'required' in schema['patternProperties']['^[A-Za-z0-9\\._%\\+-]+$']['properties']['parentContainerName']:
2171     {'properties': {'configlets': {'contains': {'type': 'string'},
2172                                    'id': 'configlets',
2173                                    'required': False,
2174                                    'type': 'array'},
2175                     'parentContainerName': {'id': 'parentContainerName',
2176                                             'required': True,
2177                                             'type': 'string'}},
2178      'required': True,
2179      'type': 'object'}
2180
2181 On instance['tp1-A']['parentContainerName']:
2182     {'parent_container': 'Tenant'}
2183 2021-03-14 17:54:36,681 - arista.cvp.container_tools_v3: ERROR - func: is_valid     (L:102) - Invalid configlet input :
2184 {'tp1-A': {'parent_container': 'Tenant'}, 'tp1-B': {'parent_container': 'tp1-A'}, 'tp1-C': {'parent_container': 'tp1-B'}, 'tp1-D': {'parent_contain     er': 'tp1-C'}}
```

which led me here: https://github.com/titom73/ansible-cvp/blob/devel-3.x/ansible_collections/arista/cvp/plugins/modules/cv_container_v3.py#L51

but I've tried with that naming convention with

```
- hosts: CloudVision
  vars:
    containers:
      tp1-A:
        parentContainerName: "Tenant"
      tp1-B:
        parentContainerName: "tp1-A"
      tp1-C:
        parentContainerName: "tp1-B"
      tp1-D:
        parentContainerName: "tp1-C"


    CVP_CONFIGLETS:
      vlan700: "vlan 700"
      vlan701: "vlan 701"

  tasks:
    - name: "Create configlet vlan 700 and 701 on {{inventory_hostname}}"
      arista.cvp.cv_configlet_v3:
        configlets: "{{CVP_CONFIGLETS}}"
        state: present

    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container_v3:
        topology: "{{containers}}"
        state: present
```

and now I'm getting this:


```
fatal: [CloudVision]: FAILED! => changed=false
  module_stderr: |-
    /Users/tamas/.pyenv/versions/3.8.6/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.83.12.79'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    Traceback (most recent call last):
      File "/Users/tamas/.ansible/tmp/ansible-local-13977ls0lsjh2/ansible-tmp-1615745080.709273-14022-263439826870697/AnsiballZ_cv_container_v3.py", line 102, in <module>
        _ansiballz_main()
      File "/Users/tamas/.ansible/tmp/ansible-local-13977ls0lsjh2/ansible-tmp-1615745080.709273-14022-263439826870697/AnsiballZ_cv_container_v3.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/Users/tamas/.ansible/tmp/ansible-local-13977ls0lsjh2/ansible-tmp-1615745080.709273-14022-263439826870697/AnsiballZ_cv_container_v3.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.arista.cvp.plugins.modules.cv_container_v3', init_globals=None, run_name='__main__', alter_sys=True)
      File "/Users/tamas/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/Users/tamas/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/Users/tamas/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/var/folders/nc/chjjl2jn43j0y5jtc60xlr0c0000gn/T/ansible_arista.cvp.cv_container_v3_payload_bw6wjefc/ansible_arista.cvp.cv_container_v3_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_container_v3.py", line 274, in <module>
      File "/var/folders/nc/chjjl2jn43j0y5jtc60xlr0c0000gn/T/ansible_arista.cvp.cv_container_v3_payload_bw6wjefc/ansible_arista.cvp.cv_container_v3_payload.zip/ansible_collections/arista/cvp/plugins/module_utils/container_tools.py", line 783, in build_topology
      File "/var/folders/nc/chjjl2jn43j0y5jtc60xlr0c0000gn/T/ansible_arista.cvp.cv_container_v3_payload_bw6wjefc/ansible_arista.cvp.cv_container_v3_payload.zip/ansible_collections/arista/cvp/plugins/module_utils/container_tools.py", line 591, in create_container
      File "/var/folders/nc/chjjl2jn43j0y5jtc60xlr0c0000gn/T/ansible_arista.cvp.cv_container_v3_payload_bw6wjefc/ansible_arista.cvp.cv_container_v3_payload.zip/ansible_collections/arista/cvp/plugins/module_utils/container_tools.py", line 553, in is_container_exists
      File "/Users/tamas/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cvprac/cvp_api.py", line 966, in get_container_by_name
        '&startIndex=0&endIndex=0' % qplus(name))
      File "/Users/tamas/.pyenv/versions/3.8.6/lib/python3.8/urllib/parse.py", line 855, in quote_plus
        string = quote(string, safe + space, encoding, errors)
      File "/Users/tamas/.pyenv/versions/3.8.6/lib/python3.8/urllib/parse.py", line 839, in quote
        return quote_from_bytes(string, safe)
      File "/Users/tamas/.pyenv/versions/3.8.6/lib/python3.8/urllib/parse.py", line 864, in quote_from_bytes
        raise TypeError("quote_from_bytes() expected bytes")
    TypeError: quote_from_bytes() expected bytes
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP *********************************************************************************************************************************************
CloudVision                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by guillaumeVilar** [comment]
Indeed, I have the same error now, thanks Tamas. 
It looks like we are checking if the parent container of 'A' exists. 
But the parent of A is set to None: 
```
2021-03-14 18:28:04,880 - arista.cvp.container_tools_v3: INFO - func: build_topology (L:783) - Start creation process for container A under None
```
Then we have this cvprac exception as we are checking if a None container exists on the CVP server.

**Comment by titom73** [comment]
Just tested with @noredistribution and it has been fixed by a previous commit.

**Comment by noredistribution** [comment]
Works fine after that latest commit:
 
```
ansible-playbook cvfast.yaml

PLAY [CloudVision] ***********************************************************************************

TASK [Create configlet vlan 700 and 701 on CloudVision] **********************************************
Tuesday 16 March 2021  21:13:12 +0000 (0:00:00.097)       0:00:00.097 *********
Tuesday 16 March 2021  21:13:12 +0000 (0:00:00.096)       0:00:00.096 *********
ok: [CloudVision]

TASK [Build Container topology on CloudVision] *******************************************************
Tuesday 16 March 2021  21:13:21 +0000 (0:00:08.495)       0:00:08.592 *********
Tuesday 16 March 2021  21:13:21 +0000 (0:00:08.495)       0:00:08.591 *********
changed: [CloudVision]

PLAY RECAP *******************************************************************************************
CloudVision                : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Tuesday 16 March 2021  21:13:40 +0000 (0:00:19.625)       0:00:28.217 *********
===============================================================================
arista.cvp.cv_container_v3 --------------------------------------------- 19.63s
arista.cvp.cv_configlet_v3 ---------------------------------------------- 8.50s
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
total ------------------------------------------------------------------ 28.12s
Tuesday 16 March 2021  21:13:40 +0000 (0:00:19.625)       0:00:28.217 *********
===============================================================================
Build Container topology on CloudVision ------------------------------------------------------ 19.63s
Create configlet vlan 700 and 701 on CloudVision ---------------------------------------------- 8.50s
Playbook run took 0 days, 0 hours, 0 minutes, 28 seconds
```

**Comment by guillaumeVilar** [comment]
Hi, 

I tested the device_v3 module today. 
FWIW, I used the following playbook (where the device `gigi-DC1-LEAF1A` is already onboarded under undefinied container, and container `B` and configlet `gigi-DC1-LEAF1A-configlet` exist): 
```
- hosts: cv_server
  vars:
    devices: 
      - fqdn: gigi-DC1-LEAF1A
        parentContainerName: 'B'
        configlets:
          - 'gigi-DC1-LEAF1A-configlet'
  tasks:
    - name: "Add device gigi-DC1-LEAF1A to container B"
      arista.cvp.cv_device_v3:
        devices: "{{devices}}"
        state: present

```

I noticed a couple of issues: 

**Issue 1: Typo in the example:** 
```
      vars:
        CVP_DEVICES:
          - fqdn: CV-ANSIBLE-EOS01
            parentContainerName: 'ANSIBLE'
            configlets:'    <<<<<<< Typo here, there is an unexpected single quote.
                - 'CV-EOS-ANSIBLE01'
```
I saw this typo in several places, unfortunately. 


**Issue 2: Unable to test the module as my topology is always not valid:** 
```
TASK [Add device gigi-DC1-LEAF1A to container B] ********************************************************************************************************************************************************************************
fatal: [cv_server]: FAILED! => changed=false 
  msg: |-
    Error, your input is not valid against current schema:
     [{'fqdn': 'gigi-DC1-LEAF1A', 'parentContainerName': 'B', 'configlets': ['gigi-DC1-LEAF1A-configlet']}]

PLAY RECAP **********************************************************************************************************************************************************************************************************************
cv_server                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

This is due to the fact that in plugins/modules/cv_device_v3.py, we have the following: 
```
    if user_topology.is_valid:
        ansible_module.fail_json(
            msg='Error, your input is not valid against current schema:\n {}'.format(ansible_module.params['devices']))
```

We should have the following line instead: 
```
    if user_topology.is_valid is False:
```

I tested locally with that change and I was able to use the collection. 

**Issue 3: If my device is in an undefinied container the cv_device fails with a cvprac error:  **
```
      warnings.warn(
    Traceback (most recent call last):
      File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_v3_payload_3koxao9w/ansible_arista.cvp.cv_device_v3_payload.zip/ansible_collections/arista/cvp/plugins/module_utils/device_tools.py", line 361, in apply_configlets
      File "/Users/guillaumevilar/Documents/avd-base-repo/venv/lib/python3.9/site-packages/cvprac/cvp_api.py", line 1208, in apply_configlets_to_device
        self._add_temp_action(data)
      File "/Users/guillaumevilar/Documents/avd-base-repo/venv/lib/python3.9/site-packages/cvprac/cvp_api.py", line 1126, in _add_temp_action
        self.clnt.post(url, data=data, timeout=self.request_timeout)
      File "/Users/guillaumevilar/Documents/avd-base-repo/venv/lib/python3.9/site-packages/cvprac/cvp_client.py", line 881, in post
        return self._make_request('POST', url, timeout, data=data, files=files)
      File "/Users/guillaumevilar/Documents/avd-base-repo/venv/lib/python3.9/site-packages/cvprac/cvp_client.py", line 632, in _make_request
        raise error
      File "/Users/guillaumevilar/Documents/avd-base-repo/venv/lib/python3.9/site-packages/cvprac/cvp_client.py", line 624, in _make_request
        response = self._send_request(req_type, full_url, timeout,
      File "/Users/guillaumevilar/Documents/avd-base-repo/venv/lib/python3.9/site-packages/cvprac/cvp_client.py", line 804, in _send_request
        raise error
      File "/Users/guillaumevilar/Documents/avd-base-repo/venv/lib/python3.9/site-packages/cvprac/cvp_client.py", line 768, in _send_request
        self._is_good_response(response, '%s: %s ' %
      File "/Users/guillaumevilar/Documents/avd-base-repo/venv/lib/python3.9/site-packages/cvprac/cvp_client.py", line 410, in _is_good_response
        raise CvpApiError(msg)
    cvprac.cvp_client_errors.CvpApiError: POST: https://10.83.12.79:443/web/provisioning/addTempAction.do?format=topology&queryParam=&nodeId=root : Request Error: Cannot assign configlet, since device is under undefined container
  
    During handling of the above exception, another exception occurred:
```

And from the logs: 
```
2021-03-17 23:09:05,719 - cvprac      : ERROR - func: _is_good_response (L:409) - POST: https://10.83.12.79:443/web/provisioning/addTempAction.do?format=topology&queryParam=&nodeId=root : Request Error: Cannot assign configlet, since device is under undefined container

```

So several questions related to this: 
> Should we handle better this error? 
> Are we suppose to move the device to the right container before using the cv_device_v3 module? If yes, which module? 
IMHO, I personally feel it would be more user friendly for the module to handle it, i.e. move the device to the specified container and then apply/remove the configlets. 

Let me know what you think. 

On a side note, is there any way I can do commit to a PR? I feel like I could solve myself Issue 1 and 2.

**Comment by titom73** [comment]
Hello @guillaumeVilar 

Thanks for these feedbacks. 

- Issue 1: Demo gist is now referenced in PR description and does not have issue you reported.
- Issue 2: Fixed has been pushed
- Issue 3: Onboarding is not yet tested and I assume we need to fine tune order of internal task execution. But definitely, target is to support onboarding.

Let's talk in 1:1 how to contribute

**Comment by titom73** [comment]
Deploy device from undefined container is now available as a beta and needs to be deeply tested.

**Pull request closed without merging**
