### PR TITLE
Feat: request add support for access point provisioning

### LINKED ISSUE #525: Feature request add support for access point provisioning
### Enhancement summary

access points rely on dhcp option 15 (domain-name) support for provisioning. 

### Which component of AVD is impacted

other

### Use case example

When an access point boots, it relies on information from dhcp.  In the case of a single provisioning cluster, dhcp option 15 is sufficient.  In more complex environments, options 43/60 can be used.  

### Describe the solution you'd like

Under the existing subnet key, add a new key called `domain_name`
```
general:            < Section to define subnets parameters >
    subnets:
      - name:         < Descriptive name, added as a comment in config file >
        network:      < * Subnet where DHCP will listen for request >
        netmask:      < * Netmask of given subnet >
        gateway:      < Gateway to configure for given subnet >
        nameservers:  < List of name-servers to configure for given subnet >
        **domain_name**: < unquoted single domain name suffix >
        **dhcpd_raw**:  | < raw configuration block >
``` 
As an example:
`domain_name: arista.com`
would output the following line in the rendered configuration
`option domain-name arista.com`

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pvinci-arista**
## Change Summary

Add dhcp support for access point provisioning

## Related Issue(s)

Fixes #525 

## Component(s) name

`arista.cvp.dhcp_configuration`

## Proposed changes
Adds the following keys:
```yaml
ztp:
  general:
    dhcpd_raw:
    subnets:
      - domain_name:
         dhcpd_raw:
```

## How to test

Molecule

`MOLECULE=dhcp_management_offline make converge`

### User Checklist

- N/A

### Repository Checklist

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [X] My change requires a change to the documentation and documentation have been updated accordingly. (check the box if not applicable)
- [X] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by noredistribution** [comment]
I ran the molecule test but doesn't seem like it generates everything:

```yaml
# Ansible managed: Do NOT edit this file manually! - dhcp_server01
# Subnet of ZTP interface
subnet 172.17.0.0 netmask 255.255.0.0 {
    range 172.17.255.200 172.17.255.200;
}

# Remote Subnet
subnet 10.255.0.0 netmask 255.255.255.0 {
    range 10.255.0.200 10.255.0.250;
    option routers 10.255.0.3;
    option domain-name-servers 10.255.0.3;
    max-lease-time 300;
}

# Per host definition
host DC1-SPINE1 {
    option host-name "DC1-SPINE1";
    hardware ethernet 0c:1d:c0:1d:62:01;
    fixed-address 10.255.0.11;
    option bootfile-name "http://10.255.0.1/ztp/bootstrap";
    option routers 10.255.0.3;
    option domain-name-servers 10.255.0.3;
}
```

vs https://github.com/aristanetworks/ansible-cvp/blob/dfcfeef2ae84b68ef272dabd61d2bb51c2e3baa0/ansible_collections/arista/cvp/molecule/dhcp_management_offline/intended/configs/dhcpd.conf

**Comment by pvinci-arista** [comment]
For molecule to run locally, we need to change https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/molecule/dhcp_management_offline/converge.yml#L11 from `name: arista.cvp.dhcp_configuration` to `name: dhcp_configuration`

**Comment by gmuloc** [comment]
> For molecule to run locally, we need to change https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/molecule/dhcp_management_offline/converge.yml#L11 from `name: arista.cvp.dhcp_configuration` to `name: dhcp_configuration`

Hi @pvinci-arista - it should not be the case .. the problem is that this molecule scenario has a collections.yml file requirement that will install `arista.avd` (??? why) and this will in turn reinstall `arista.cvp==v3.4.0` as a dependency (yeah) that will be preferred at execution time.. 


The most amazing part is that EVEN in the pipeline the file you have committed changes: https://github.com/aristanetworks/ansible-cvp/actions/runs/3139072538/jobs/5099169829#step:5:313 but somehow the check is still successful (hum ... @sugetha24  probably this needs to be investigated further).

In the meantime I have prepared a commit to push to your branch @pvinci-arista to remove the un-needed collection. could you please allow me to push to your branch? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by pvinci-arista** [comment]
@gmuloc `Allow edits by maintainers` is set.  Have I missed something?

**Comment by ClausHolbechArista** [comment]
@gmuloc you may not be a maintainer on ansible-cvp repo

**Comment by gmuloc** [comment]
Hey all -  no need to make me maintainer - @pvinci-arista gave me push access to his repo. I have added 2 commits to the PR to remove the need for AVD inside the molecule scenario for CVP .. which was only there to create a folder that already exist.

btw there is something fishy with the pipeline cf - https://github.com/aristanetworks/ansible-cvp/actions/runs/3220049173/jobs/5266285986#step:5:179 

molecule fails but still the pipeline succeeded..

it comes from this I think: https://github.com/aristanetworks/ansible-cvp/blob/devel/.github/workflows/pull-request-management.yml#L176 - probably should make it True (and see what breaks hehe)

**Review by noredistribution — APPROVED** [review]
LGTM! tested now and works fine without modifying anything

**Review by sugetha24 — APPROVED** [review]
LGTM

**Pull request merged**
