### PR TITLE
Grant release v1.0

### PR DESCRIPTION
**Pull request by titom73**
Merge for first public version of the collection.

__New Features:__

- Support for CVP __2018.2.x__ and CVP __2019.1.x__
- Implement `cv_facts` module for information gathering
- Implement `cv_container` and `cv_device` to manage provisioning topology
- Implement `cv_configlet` to manage configlet content on CloudVision platform
- Use Ansible collection approach

__Documentation__

- Modules documentation: [`docs/`](https://github.com/aristanetworks/ansible-cvp/tree/grant-release/docs) folder
- Example playbooks available in [`examples/`](https://github.com/aristanetworks/ansible-cvp/tree/grant-release/examples) folder

### CODE REVIEW

**Comment by networkop** [comment]
https://github.com/aristanetworks/ansible-cvp/blob/d822d5bc7319bf3159056640d5e005bc25a8fda9/README.md contains a dead link to cv_tasks docs

**Comment by networkop** [comment]
should we remove passwords from `inventory.ini` file?

**Comment by networkop** [comment]
should the docs have separate MD file describing authentication instead of listing it in each individual module? or will this make it more confusing?

**Comment by networkop** [comment]
otherwise LGTM

**Comment by titom73** [comment]
> should the docs have separate MD file describing authentication instead of listing it in each individual module? or will this make it more confusing?

Idea was to provide a single page per module with everything user needs to use that module in a playbook: user can refer to a single page to get module works.

We can also make an additional page with more details about how authentication works like vars and connection plugin

**Comment by networkop** [comment]
> > should the docs have separate MD file describing authentication instead of listing it in each individual module? or will this make it more confusing?
> 
> Idea was to provide a single page per module with everything user needs to use that module in a playbook: user can refer to a single page to get module works.
> 
> We can also make an additional page with more details about how authentication works like vars and connection plugin

ok, makes sense. let's leave this as it is then.

**Pull request merged**
